[tool.poetry]
name = "faqbot"
version = "0.1.0"
description = ""
authors = ["0xMRTT <0xMRTT@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
simplematrixbotlib = "^2.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
